# Stage 1: Build the React app
FROM node:18-alpine as build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY public/ public
COPY src/ src

ENV REACT_APP_BACKEND_URL=https://backend-zenvi-5zv6ce4weq-no.a.run.app/api
RUN npm run build

# Stage 2: Serve the built app with Nginx
FROM nginx:alpine

# Remove default Nginx static resources
RUN rm -rf /usr/share/nginx/html/*

# Copy built React app from Stage 1
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the port Cloud Run expects
EXPOSE 8080

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]